services:
  main-app:
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  redis: