version: "3"
services:
  main-app:
    image: arlet2/vt_polls_bot
    env_file: .env
    depends_on:
      - mongo

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
