services:
  main-app:
    container_name: bot
    build:
      context: .
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

volumes:
  redis: