services:
  main-app:
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379

volumes:
  redis:
