name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    env:
      REGISTRY: hub.docker.com
      IMAGE_NAME: vt_polls_bot
      VERSION: latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - 
      name: Build info
      run: "echo \"REGISTRY: $REGISTRY; IMAGE_NAME: $IMAGE_NAME; VERSION: $VERSION;\""
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: arlet2/"$IMAGE_NAME":"$VERSION"
