name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    env:
      REGISTRY: hub.docker.com
      IMAGE_NAME: vt_polls_bot
      VERSION: latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build info
      run: "echo \"REGISTRY: $REGISTRY; IMAGE_NAME: $IMAGE_NAME; VERSION: $VERSION; USER: ${{ secrets.DOCKERHUB_USERNAME }}\""
    - name: Log in Docker hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build --push -t ${{ secrets.DOCKERHUB_USERNAME }}/"$IMAGE_NAME":"$VERSION" .
      
